FROM golang:1.23 AS backend-builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    libvips-dev && \
    libvips=8.8.4 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV GOOS=linux
ENV GOARCH=arm64

WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN go build -ldflags "-s -w" -o discuit .

FROM node:18 AS frontend-builder

RUN corepack enable && corepack prepare pnpm@10.31.0 --activate

WORKDIR /app
COPY config.default.yaml .
RUN mv config.default.yaml config.yaml
COPY --from=backend-builder /app/discuit /app/discuit

WORKDIR /app/ui
COPY ui/package.json ui/pnpm-lock.yaml ui/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY ui/ . 

FROM node:18
ENV DEBIAN_FRONTEND=noninteractive
RUN corepack enable && corepack prepare pnpm@10.31.0 --activate

RUN apt-get update && apt-get install -y --no-install-recommends \
    redis-server \
    libvips-dev && \
    libvips=8.8.4 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=frontend-builder /app/ui /app/ui
COPY --from=backend-builder /app/discuit /app/discuit
COPY config.default.yaml /app/config.yaml
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/app/discuit", "serve"]
